language: python
python:
- '3.6'
install:
  - pip install Django
deploy:
  provider: heroku
  api_key:
    secure: 1e9SyII+lQ+SVzcd7wk468VDp2HnkCY3mIwsx4KFqA+EIKCrwFMiLWxmUn6+Qxuh5B5LAGl9i2gsVjhDGnhmJe+H8o5aawianHfUKdT1YLFMkA8AGLYvpCiGfxGGqsPfuJ3WKOw3G9HE3ncoTA9E1q/oEB8+wyn6KkjNWTUOTovQPMFJTP7CUKeED0gabuve9sfp9BEc0rge/1MU+rojYkbW3APdb6s6EYPVmF3bffyrnYHf15fuvvOQHzcr74/vK/xj3r+0zKvN8AicCqg9oW9QVExNPUk7FgkKN6B1vqB/uwZH3sXUeGv3EQjw669zwU7H4rdh6AvW+GsCSAToOWlzCmm6OpBcl9MdfKfIiZwD1H88nFHpqtPLvI9+B6yLmrnrzeKWhRgIpy7RrLHneFkPUlzxGMe0cpo7y2yW2ElQRJtw3CmsvpXF02nmwTESHXkLp/hcnogrAvlfxTkM+2+qhSrPAwneDLJCLgnpZQJOw/SusRVdB78eGzlnzRRNg10urcekO3WV7NpYUSq+jrSStnFmpeXEOcb+fTH5RB2ktfjY7uRql/5c+eFXiMb1UTDcZOFopZ8d09dbksasjQP/8fLMYV2hCEqyiAi0dHX4hmYICyHlJENF3SqhHT17npOARmZr97z6gEKbPaQ0EzaVvNDmuiGWMcsZDBsX+2w=
script: pytest
